  
version: 2
updates:
  # Updates for Github Actions used in the repo
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"

  # Maintain dependencies for core module
  - package-ecosystem: "gradle"
    directory: "/core"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "core"

  # Maintain dependencies for tizen module
  - package-ecosystem: "gradle"
    directory: "/tizen"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "tizen"

  # Maintain dependencies for wearos module
  - package-ecosystem: "gradle"
    directory: "/wearos"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "wearos"
